name: Release Alkemio package
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  Auto-release-alkemio-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        run: npm install -g npm@latest
      - name: Set up publish access
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Auto release
        run: |
          yarn
          cd packages/excalidraw
          yarn install
          yarn build:esm
          yarn pack
          yarn publish --non-interactive --new-version $(jq -r '.version' package.json) --access public
