name: Release Alkemio package
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Auto-release-alkemio-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Set up publish access
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Auto release
        run: |
          yarn
          cd packages/excalidraw
          yarn install
          yarn build:esm
          yarn pack
          yarn publish --new-version $(jq -r '.version' package.json) --access public
