name: Release Alkemio package
on:
  release:
    types: [published]
permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  Auto-release-alkemio-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - name: Auto release
        run: |
          yarn
          cd packages/excalidraw
          yarn install
          yarn build:esm
          yarn pack
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish $(ls *.tgz) --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
